all: writeint writefloat utf8coding readchar writebin

writeint: writeint.c
	gcc -o writeint writeint.c

writebin: writebin.c
	gcc -o writebin writebin.c

writefloat: writefloat.c
	gcc -o writefloat writefloat.c

utf8coding: utf8coding.c
	gcc -o utf8coding utf8coding.c

readchar: readchar.c
	gcc -o readchar readchar.c

clear:
	rm writeint writefloat utf8coding readchar writebin

