all: floats integers mems fibonacci

floats: floats.c
	gcc -o floats floats.c

integers: integers.c
	gcc -o integers integers.c

mems: mems.c
	gcc -o mems mems.c

fibonacci: fibonacci.c
	gcc -o fibonacci fibonacci.c

clean:
	rm -f floats integers mems fibonacci
